### PR TITLE
Upgrade Tabler icons to v1.119.0

### PR DESCRIPTION
**Pull request by sebastiansandqvist**
This PR bumps the Tabler icon set version from `1.70.0` to `1.119.0`, adding many new icons.

### CODE REVIEW

**Comment by sebastiansandqvist** [comment]
Not sure whether I did this correctly--I imagine one (or multiple) of the build commands need to be rerun and the package version bumped. Hoping to at least kick off the upgrade process for this icon set here, though. Let me know @x64Bits if there are changes I should make to this PR to help make that happen.

**Comment by x64Bits** [comment]
Hello @sebastiansandqvist, will review this PR, sorry for the late response i was so much busy, in first instance this looks well, but today at the end of the day i promise to review everything, thanks.

**Comment by x64Bits** [comment]
I have tried to run the build locally but I get this error:
```
var ry = item.attr('ry').value || 0;
                        ^
TypeError: Cannot read properties of undefined (reading 'value')
    at Object.exports.fn (/Users/izsabo/code/solid-icons/lib/node_modules/svgo/plugins/convertEllipseToCircle.js:22:31)
```

It seems to be related with SVGO the lib are currently using an old version for the svg optimization, @aminya have this PR open, i'm going to take a look this tomorrow, merge that PR first.

**Comment by x64Bits** [comment]
I'm currently building and uploading the icons with the **table icons v1.119.0**, thanks for the contribution.

**Pull request merged**
